# for the ai-platform (unified) API
workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  containerSpec:
    imageUri: 
    args:
    - data-path=data
    - bucket-name=python-trained-models
    - epochs=20
